// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: shipment.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED ShipmentStatus = 0
	ShipmentStatus_SHIPMENT_STATUS_CREATED     ShipmentStatus = 1
	ShipmentStatus_SHIPMENT_STATUS_DISPATCHED  ShipmentStatus = 2
	ShipmentStatus_SHIPMENT_STATUS_DELIVERED   ShipmentStatus = 3
	ShipmentStatus_SHIPMENT_STATUS_FAILED      ShipmentStatus = 4
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_UNSPECIFIED",
		1: "SHIPMENT_STATUS_CREATED",
		2: "SHIPMENT_STATUS_DISPATCHED",
		3: "SHIPMENT_STATUS_DELIVERED",
		4: "SHIPMENT_STATUS_FAILED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_UNSPECIFIED": 0,
		"SHIPMENT_STATUS_CREATED":     1,
		"SHIPMENT_STATUS_DISPATCHED":  2,
		"SHIPMENT_STATUS_DELIVERED":   3,
		"SHIPMENT_STATUS_FAILED":      4,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipment_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipment_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

type ShipmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentItem) Reset() {
	*x = ShipmentItem{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentItem) ProtoMessage() {}

func (x *ShipmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentItem.ProtoReflect.Descriptor instead.
func (*ShipmentItem) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *ShipmentItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentItem) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type Shipment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId      string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AddressSnapshot *Address               `protobuf:"bytes,3,opt,name=address_snapshot,json=addressSnapshot,proto3" json:"address_snapshot,omitempty"`
	Items           []*ShipmentItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Status          ShipmentStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=api.ShipmentStatus" json:"status,omitempty"`
	Carrier         string                 `protobuf:"bytes,6,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrackingNumber  string                 `protobuf:"bytes,7,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix   int64                  `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *Shipment) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *Shipment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Shipment) GetAddressSnapshot() *Address {
	if x != nil {
		return x.AddressSnapshot
	}
	return nil
}

func (x *Shipment) GetItems() []*ShipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *Shipment) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Shipment) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type CreateShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AddressSnapshot *Address               `protobuf:"bytes,2,opt,name=address_snapshot,json=addressSnapshot,proto3" json:"address_snapshot,omitempty"`
	Items           []*ShipmentItem        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShipmentRequest) GetAddressSnapshot() *Address {
	if x != nil {
		return x.AddressSnapshot
	}
	return nil
}

func (x *CreateShipmentRequest) GetItems() []*ShipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateShipmentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentReply) Reset() {
	*x = CreateShipmentReply{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentReply) ProtoMessage() {}

func (x *CreateShipmentReply) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentReply.ProtoReflect.Descriptor instead.
func (*CreateShipmentReply) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentReply) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentReply) Reset() {
	*x = GetShipmentReply{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentReply) ProtoMessage() {}

func (x *GetShipmentReply) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentReply.ProtoReflect.Descriptor instead.
func (*GetShipmentReply) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentReply) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\x03api\x1a\fcommon.proto\"2\n" +
	"\fShipmentItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\"\xe8\x02\n" +
	"\bShipment\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x127\n" +
	"\x10address_snapshot\x18\x03 \x01(\v2\f.api.AddressR\x0faddressSnapshot\x12'\n" +
	"\x05items\x18\x04 \x03(\v2\x11.api.ShipmentItemR\x05items\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.api.ShipmentStatusR\x06status\x12\x18\n" +
	"\acarrier\x18\x06 \x01(\tR\acarrier\x12'\n" +
	"\x0ftracking_number\x18\a \x01(\tR\x0etrackingNumber\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnix\"\x94\x01\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x127\n" +
	"\x10address_snapshot\x18\x02 \x01(\v2\f.api.AddressR\x0faddressSnapshot\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.api.ShipmentItemR\x05items\"@\n" +
	"\x13CreateShipmentReply\x12)\n" +
	"\bshipment\x18\x01 \x01(\v2\r.api.ShipmentR\bshipment\"5\n" +
	"\x12GetShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"=\n" +
	"\x10GetShipmentReply\x12)\n" +
	"\bshipment\x18\x01 \x01(\v2\r.api.ShipmentR\bshipment*\xa9\x01\n" +
	"\x0eShipmentStatus\x12\x1f\n" +
	"\x1bSHIPMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_CREATED\x10\x01\x12\x1e\n" +
	"\x1aSHIPMENT_STATUS_DISPATCHED\x10\x02\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_DELIVERED\x10\x03\x12\x1a\n" +
	"\x16SHIPMENT_STATUS_FAILED\x10\x042\x98\x01\n" +
	"\x0fShipmentService\x12F\n" +
	"\x0eCreateShipment\x12\x1a.api.CreateShipmentRequest\x1a\x18.api.CreateShipmentReply\x12=\n" +
	"\vGetShipment\x12\x17.api.GetShipmentRequest\x1a\x15.api.GetShipmentReplyB\aZ\x05.;apib\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shipment_proto_goTypes = []any{
	(ShipmentStatus)(0),           // 0: api.ShipmentStatus
	(*ShipmentItem)(nil),          // 1: api.ShipmentItem
	(*Shipment)(nil),              // 2: api.Shipment
	(*CreateShipmentRequest)(nil), // 3: api.CreateShipmentRequest
	(*CreateShipmentReply)(nil),   // 4: api.CreateShipmentReply
	(*GetShipmentRequest)(nil),    // 5: api.GetShipmentRequest
	(*GetShipmentReply)(nil),      // 6: api.GetShipmentReply
	(*Address)(nil),               // 7: api.Address
}
var file_shipment_proto_depIdxs = []int32{
	7, // 0: api.Shipment.address_snapshot:type_name -> api.Address
	1, // 1: api.Shipment.items:type_name -> api.ShipmentItem
	0, // 2: api.Shipment.status:type_name -> api.ShipmentStatus
	7, // 3: api.CreateShipmentRequest.address_snapshot:type_name -> api.Address
	1, // 4: api.CreateShipmentRequest.items:type_name -> api.ShipmentItem
	2, // 5: api.CreateShipmentReply.shipment:type_name -> api.Shipment
	2, // 6: api.GetShipmentReply.shipment:type_name -> api.Shipment
	3, // 7: api.ShipmentService.CreateShipment:input_type -> api.CreateShipmentRequest
	5, // 8: api.ShipmentService.GetShipment:input_type -> api.GetShipmentRequest
	4, // 9: api.ShipmentService.CreateShipment:output_type -> api.CreateShipmentReply
	6, // 10: api.ShipmentService.GetShipment:output_type -> api.GetShipmentReply
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		EnumInfos:         file_shipment_proto_enumTypes,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
