// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: stock.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_OK          ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_PARTIAL     ReservationStatus = 2
	ReservationStatus_RESERVATION_STATUS_FAILED      ReservationStatus = 3
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_OK",
		2: "RESERVATION_STATUS_PARTIAL",
		3: "RESERVATION_STATUS_FAILED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_OK":          1,
		"RESERVATION_STATUS_PARTIAL":     2,
		"RESERVATION_STATUS_FAILED":      3,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stock_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_stock_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	AvailableQty  int64                  `protobuf:"varint,2,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	ReservedQty   int64                  `protobuf:"varint,3,opt,name=reserved_qty,json=reservedQty,proto3" json:"reserved_qty,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockItem) GetAvailableQty() int64 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

func (x *StockItem) GetReservedQty() int64 {
	if x != nil {
		return x.ReservedQty
	}
	return 0
}

func (x *StockItem) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type ReserveItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Lines         []*ItemLine            `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsRequest) GetLines() []*ItemLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ReserveItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReservationStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=api.ReservationStatus" json:"status,omitempty"`
	Reserved      []*ItemLine            `protobuf:"bytes,2,rep,name=reserved,proto3" json:"reserved,omitempty"`
	Missing       []*ItemLine            `protobuf:"bytes,3,rep,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsReply) Reset() {
	*x = ReserveItemsReply{}
	mi := &file_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsReply) ProtoMessage() {}

func (x *ReserveItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsReply.ProtoReflect.Descriptor instead.
func (*ReserveItemsReply) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveItemsReply) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *ReserveItemsReply) GetReserved() []*ItemLine {
	if x != nil {
		return x.Reserved
	}
	return nil
}

func (x *ReserveItemsReply) GetMissing() []*ItemLine {
	if x != nil {
		return x.Missing
	}
	return nil
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseReservationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationReply) Reset() {
	*x = ReleaseReservationReply{}
	mi := &file_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationReply) ProtoMessage() {}

func (x *ReleaseReservationReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationReply.ProtoReflect.Descriptor instead.
func (*ReleaseReservationReply) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseReservationReply) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type GetStockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *StockItem             `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReply) Reset() {
	*x = GetStockReply{}
	mi := &file_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReply) ProtoMessage() {}

func (x *GetStockReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReply.ProtoReflect.Descriptor instead.
func (*GetStockReply) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockReply) GetStock() *StockItem {
	if x != nil {
		return x.Stock
	}
	return nil
}

func (x *GetStockReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x03api\x1a\fcommon.proto\"\x8e\x01\n" +
	"\aProduct\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\x8d\x01\n" +
	"\tStockItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12#\n" +
	"\ravailable_qty\x18\x02 \x01(\x03R\favailableQty\x12!\n" +
	"\freserved_qty\x18\x03 \x01(\x03R\vreservedQty\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix\"U\n" +
	"\x13ReserveItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12#\n" +
	"\x05lines\x18\x02 \x03(\v2\r.api.ItemLineR\x05lines\"\x97\x01\n" +
	"\x11ReserveItemsReply\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.api.ReservationStatusR\x06status\x12)\n" +
	"\breserved\x18\x02 \x03(\v2\r.api.ItemLineR\breserved\x12'\n" +
	"\amissing\x18\x03 \x03(\v2\r.api.ItemLineR\amissing\"6\n" +
	"\x19ReleaseReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"5\n" +
	"\x17ReleaseReservationReply\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"#\n" +
	"\x0fGetStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\"]\n" +
	"\rGetStockReply\x12$\n" +
	"\x05stock\x18\x01 \x01(\v2\x0e.api.StockItemR\x05stock\x12&\n" +
	"\aproduct\x18\x02 \x01(\v2\f.api.ProductR\aproduct*\x91\x01\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESERVATION_STATUS_OK\x10\x01\x12\x1e\n" +
	"\x1aRESERVATION_STATUS_PARTIAL\x10\x02\x12\x1d\n" +
	"\x19RESERVATION_STATUS_FAILED\x10\x032\xda\x01\n" +
	"\fStockService\x12@\n" +
	"\fReserveItems\x12\x18.api.ReserveItemsRequest\x1a\x16.api.ReserveItemsReply\x12R\n" +
	"\x12ReleaseReservation\x12\x1e.api.ReleaseReservationRequest\x1a\x1c.api.ReleaseReservationReply\x124\n" +
	"\bGetStock\x12\x14.api.GetStockRequest\x1a\x12.api.GetStockReplyB\aZ\x05.;apib\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stock_proto_goTypes = []any{
	(ReservationStatus)(0),            // 0: api.ReservationStatus
	(*Product)(nil),                   // 1: api.Product
	(*StockItem)(nil),                 // 2: api.StockItem
	(*ReserveItemsRequest)(nil),       // 3: api.ReserveItemsRequest
	(*ReserveItemsReply)(nil),         // 4: api.ReserveItemsReply
	(*ReleaseReservationRequest)(nil), // 5: api.ReleaseReservationRequest
	(*ReleaseReservationReply)(nil),   // 6: api.ReleaseReservationReply
	(*GetStockRequest)(nil),           // 7: api.GetStockRequest
	(*GetStockReply)(nil),             // 8: api.GetStockReply
	(*ItemLine)(nil),                  // 9: api.ItemLine
}
var file_stock_proto_depIdxs = []int32{
	9, // 0: api.ReserveItemsRequest.lines:type_name -> api.ItemLine
	0, // 1: api.ReserveItemsReply.status:type_name -> api.ReservationStatus
	9, // 2: api.ReserveItemsReply.reserved:type_name -> api.ItemLine
	9, // 3: api.ReserveItemsReply.missing:type_name -> api.ItemLine
	2, // 4: api.GetStockReply.stock:type_name -> api.StockItem
	1, // 5: api.GetStockReply.product:type_name -> api.Product
	3, // 6: api.StockService.ReserveItems:input_type -> api.ReserveItemsRequest
	5, // 7: api.StockService.ReleaseReservation:input_type -> api.ReleaseReservationRequest
	7, // 8: api.StockService.GetStock:input_type -> api.GetStockRequest
	4, // 9: api.StockService.ReserveItems:output_type -> api.ReserveItemsReply
	6, // 10: api.StockService.ReleaseReservation:output_type -> api.ReleaseReservationReply
	8, // 11: api.StockService.GetStock:output_type -> api.GetStockReply
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		EnumInfos:         file_stock_proto_enumTypes,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
