// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: supplier.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierName  string                 `protobuf:"bytes,1,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Lines         []*ItemLine            `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveStockRequest) Reset() {
	*x = ReceiveStockRequest{}
	mi := &file_supplier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveStockRequest) ProtoMessage() {}

func (x *ReceiveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveStockRequest.ProtoReflect.Descriptor instead.
func (*ReceiveStockRequest) Descriptor() ([]byte, []int) {
	return file_supplier_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiveStockRequest) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *ReceiveStockRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ReceiveStockRequest) GetLines() []*ItemLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ReceiveStockReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ReceivedAtUnix int64                  `protobuf:"varint,2,opt,name=received_at_unix,json=receivedAtUnix,proto3" json:"received_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReceiveStockReply) Reset() {
	*x = ReceiveStockReply{}
	mi := &file_supplier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveStockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveStockReply) ProtoMessage() {}

func (x *ReceiveStockReply) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveStockReply.ProtoReflect.Descriptor instead.
func (*ReceiveStockReply) Descriptor() ([]byte, []int) {
	return file_supplier_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveStockReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReceiveStockReply) GetReceivedAtUnix() int64 {
	if x != nil {
		return x.ReceivedAtUnix
	}
	return 0
}

var File_supplier_proto protoreflect.FileDescriptor

const file_supplier_proto_rawDesc = "" +
	"\n" +
	"\x0esupplier.proto\x12\x03api\x1a\fcommon.proto\"}\n" +
	"\x13ReceiveStockRequest\x12#\n" +
	"\rsupplier_name\x18\x01 \x01(\tR\fsupplierName\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12#\n" +
	"\x05lines\x18\x03 \x03(\v2\r.api.ItemLineR\x05lines\"Y\n" +
	"\x11ReceiveStockReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12(\n" +
	"\x10received_at_unix\x18\x02 \x01(\x03R\x0ereceivedAtUnix2S\n" +
	"\x0fSupplierService\x12@\n" +
	"\fReceiveStock\x12\x18.api.ReceiveStockRequest\x1a\x16.api.ReceiveStockReplyB\aZ\x05.;apib\x06proto3"

var (
	file_supplier_proto_rawDescOnce sync.Once
	file_supplier_proto_rawDescData []byte
)

func file_supplier_proto_rawDescGZIP() []byte {
	file_supplier_proto_rawDescOnce.Do(func() {
		file_supplier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supplier_proto_rawDesc), len(file_supplier_proto_rawDesc)))
	})
	return file_supplier_proto_rawDescData
}

var file_supplier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_supplier_proto_goTypes = []any{
	(*ReceiveStockRequest)(nil), // 0: api.ReceiveStockRequest
	(*ReceiveStockReply)(nil),   // 1: api.ReceiveStockReply
	(*ItemLine)(nil),            // 2: api.ItemLine
}
var file_supplier_proto_depIdxs = []int32{
	2, // 0: api.ReceiveStockRequest.lines:type_name -> api.ItemLine
	0, // 1: api.SupplierService.ReceiveStock:input_type -> api.ReceiveStockRequest
	1, // 2: api.SupplierService.ReceiveStock:output_type -> api.ReceiveStockReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_supplier_proto_init() }
func file_supplier_proto_init() {
	if File_supplier_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supplier_proto_rawDesc), len(file_supplier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supplier_proto_goTypes,
		DependencyIndexes: file_supplier_proto_depIdxs,
		MessageInfos:      file_supplier_proto_msgTypes,
	}.Build()
	File_supplier_proto = out.File
	file_supplier_proto_goTypes = nil
	file_supplier_proto_depIdxs = nil
}
